### ISSUE TITLE
Run  time error 

### ISSUE THREAD

**Issue by CaffineAddic** [scikit-learn-contrib/hdbscan#518] opened 2022-01-09 09:56 UTC
When I try to run I get greeted with this error code 
I tried running 
python -m nose -s hdbscan
but it also gave similar error 
E
======================================================================
ERROR: Failure: ValueError (numpy.ndarray size changed, may indicate binary incompatibility. Expected 96
 from C header, got 88 from PyObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kira/Desktop/notebook/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTe
st
    raise self.exc_val.with_traceback(self.tb)
  File "/home/kira/Desktop/notebook/venv/lib/python3.8/site-packages/nose/loader.py", line 407, in loadT
estsFromName
    module = resolve_name(addr.module)
  File "/home/kira/Desktop/notebook/venv/lib/python3.8/site-packages/nose/util.py", line 312, in resolve
_name
    module = __import__('.'.join(parts_copy))
  File "/home/kira/Desktop/notebook/venv/lib/python3.8/site-packages/hdbscan/__init__.py", line 1, in <m
odule>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/kira/Desktop/notebook/venv/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 21, in <
module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header,
got 88 from PyObject

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by sk1p** [comment] 2022-01-10 15:12
Seems to be a duplicate of https://github.com/scikit-learn-contrib/hdbscan/issues/457 - which is fixed in master, but not yet released on PyPI

**Closed** 2022-01-10 17:25 UTC
