### ISSUE TITLE
some cluster_persistence_ outputs are greater than 1?

### ISSUE THREAD

**Issue by titaniumrain** [scikit-learn-contrib/hdbscan#84] opened 2017-01-29 22:29 UTC
Hi,

Quick question though, according to HDBSCAN documentation, if my interpretation is correct cluster_persistence_ outputs should be [0, 1]. 

However, I got some weird results like 2.81 as shown below.

import numpy as np
np.round(clusters.cluster_persistence_, 2)
​
Out[34]:
array([ 2.81,  0.  ,  0.44,  0.  ,  0.  ,  0.  ,  0.02,  0.  ,  0.  ,
        0.  ,  0.  ,  0.11,  0.01,  0.  ,  0.01,  0.  ,  0.  ,  0.  ,
        0.01,  0.  ,  0.04,  0.07,  0.  ,  0.03,  0.  ,  0.  ,  0.  ,
        0.01,  0.  ,  0.  ,  0.01,  0.  ,  0.  ,  0.  ,  0.01,  0.01,
        0.03,  0.  ,  0.03,  0.  ,  0.01,  0.01,  0.01,  0.01,  0.  ,
        0.02,  0.  ,  0.18,  0.  ,  0.  ,  0.  ,  1.06,  0.37,  0.61,
        0.77,  0.  ,  0.09,  0.  ,  0.23,  0.74,  0.  ,  0.24,  1.1 ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.01,  0.01,  0.01,
        0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.06,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.03,  0.01,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.01,  0.  ,  0.03,  0.03,  0.01,
        0.04,  0.  ,  0.  ,  0.  ,  0.01,  0.  ,  0.01,  0.  ,  0.  ,
        0.  ,  0.  ,  0.01,  0.  ,  0.01,  0.  ,  0.  ,  0.02,  0.  ,  0.  ])

Am I doing things wrong?

Cheers,

Titan

**Comment by lmcinnes** [comment] 2017-01-29 22:40
Nope, that's a bug. Can you share the data set or provide a small
reproducer? If not I'll just g through the code and see if I can see
anything off.

**Comment by titaniumrain** [comment] 2017-01-30 16:15
Thanks for getting back so promptly. Very much appreciated. 

Sample data is attached.


[sample.out.zip](https://github.com/scikit-learn-contrib/hdbscan/files/739510/sample.out.zip)

**Comment by lmcinnes** [comment] 2017-01-30 18:49
Thanks so much -- I know data isn't always easy to share, so this is
greatly appreciated. I should have some time tonight if all goes well.

**Comment by lmcinnes** [comment] 2017-01-31 21:29
I believe this may be a bug I accidentally introduced recently. I'm still looking into it.

**Comment by lmcinnes** [comment] 2017-02-01 02:32
So it turns out that in a previous clean up I made the cluster labelling order consistent across approaches, but in so doing I missed the fact that the cluster persistence scores also depend on the order, so the scores were getting normalized by the wrong cluster sizes (labels not matching condensed tree cluster ids). It's fixed in master now. I'll try and get a new point release out soon.

**Comment by titaniumrain** [comment] 2017-02-01 11:30
Thanks a lot for sorting out this issue :) Very very much appreciated.

**Comment by titaniumrain** [comment] 2017-02-01 11:59
Hi Leland,

Quick feedback. I can confirm that cluster_persistence_ output is normalised to 1. 

And one very very minor note, the new version 0.8.6 prints out cluster information by default. It would be great that it can be turned off somehow. 

Many thanks again.

**Comment by lmcinnes** [comment] 2017-02-01 14:11
Hmm, I was pretty sure I had deleted that line. Sorry about that! Let me
fix it.

**Comment by lmcinnes** [comment] 2017-02-01 14:13
Actually the debugging lines I thought were causing this were removed, so
it must be something else. I will need to wait until I can get to a system
I can test on properly. Don't worry,it'll get fixed soon.

**Comment by lmcinnes** [comment] 2017-02-03 03:53
Fixed now. Closing.

**Closed by lmcinnes** 2017-02-03 03:53 UTC

**Comment by titaniumrain** [comment] 2017-02-04 09:33
thanks. 0.8.7 works as a breeze :)
