### ISSUE TITLE
Import of hdbscan==0.8.20 fails with scikit-learn==0.21.0

### ISSUE THREAD

**Issue by uellue** [scikit-learn-contrib/hdbscan#296] opened 2019-05-10 08:32 UTC
If scikit-learn is installed in version 0.21.0, importing hdbscan in version 0.8.20 gives the following error:

```
~/libertem-venv/lib/python3.6/site-packages/hdbscan/__init__.py in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import approximate_predict, membership_vector, all_points_membership_vectors
      5 

~/libertem-venv/lib/python3.6/site-packages/hdbscan/hdbscan_.py in <module>
     15 from warnings import warn
     16 from sklearn.utils import check_array
---> 17 from sklearn.externals.joblib.parallel import cpu_count
     18 
     19 from scipy.sparse import csgraph

ModuleNotFoundError: No module named 'sklearn.externals.joblib.parallel'
```

Downgrading to scikit-learn==0.20.2 works around the issue.

**Comment by danilomendesdias** [comment] 2019-05-10 12:45
I can confirm the same problem.

**Comment by lmcinnes** [comment] 2019-05-13 16:45
PR #297 should fix this -- hopefully I'll get a release with the fix out soon.

**Comment by rana-alshaikh** [comment] 2019-08-15 12:50
is there any solution for this issue

**Comment by YairMazor** [comment] 2020-04-15 14:14
Is there and update on this?
It is my understanding that any scikit-learn version >= 0.21.0 will have this conflict (I'm using 0.22.2) . 
Downgrading to version 0.20 is not an option for me and it seems like a dead end at the moment.

**Comment by lmcinnes** [comment] 2020-04-15 14:47
I believe this was fixed in the more recent hdbscan releases with joblib handled separately.

**Comment by YairMazor** [comment] 2020-04-15 17:56
Thank you for you prompt response.

After successfully installing the latest version using pip the problem was indeed resolved. 
(I had another problem with python 3.6 and the enum library that I had to removed, that might have confused me). 

Perhaps worth closing this ticket?


BTW, These are the current version dependencies: 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/11959288/79369808-3ae39900-7f5a-11ea-81a1-cb6dd4c09fb8.png">

**Comment by lmcinnes** [comment] 2020-04-15 18:05
Thanks; glad it indeed works now.

**Closed by lmcinnes** 2020-04-15 18:05 UTC

**Comment by cjsmith015** [comment] 2021-03-18 20:06
I am having this same issue. I've tried installing the hdbscan library via pip and conda, both of which are updated.

`hdbscan==0.8.19
sklearn==0.24.1
conda==4.9.2
pip==21.0.1
python==3.7.7`

When I try to import hdbscan in python, I get this error:
`ModuleNotFoundError: No module named 'sklearn.externals.joblib'`

Is there a way to solve this? I'd prefer not to downgrade my versions of packages, if it's possible.
