### ISSUE TITLE
numpy  incompatibility

### ISSUE THREAD

**Issue by srsani** [scikit-learn-contrib/hdbscan#520] opened 2022-01-19 16:46 UTC
I get the following when I try to `import hdbscan`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <module>
----> 1 import hdbscan

File ~/Projects/cltv-product/env/lib/python3.9/site-packages/hdbscan/__init__.py:1, in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index

File ~/Projects/cltv-product/env/lib/python3.9/site-packages/hdbscan/hdbscan_.py:21, in <module>
     17 from joblib.parallel import cpu_count
     19 from scipy.sparse import csgraph
---> 21 from ._hdbscan_linkage import (single_linkage,
     22                                mst_linkage_core,
     23                                mst_linkage_core_vector,
     24                                label)
     25 from ._hdbscan_tree import (condense_tree,
     26                             compute_stability,
     27                             get_clusters,
     28                             outlier_scores)
     29 from ._hdbscan_reachability import (mutual_reachability,
     30                                     sparse_mutual_reachability)

File hdbscan/_hdbscan_linkage.pyx:1, in init hdbscan._hdbscan_linkage()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

numba             0.55.0
numpy             1.21.5

Can you please let me know how I should fix this issue? 

Thanks

**Comment by Kydlaw** [comment] 2022-01-19 17:28
Duplicate of #457

The issue is quite tricky as you'll see in the discussion in the issue mentioned.
Reinstalling Numpy, Numba et HDBSCAN in a new environment with the right versions seems to fix it however.

I tried recently with:

Python 3.9.7
Numpy 1.22.0
Numba 0.53.0
Pynndescent 0.5.5
HDBSCAN 0.8.27

and it worked for me. I hope it will for you too.

**Comment by srsani** [comment] 2022-01-19 17:49
Thanks @Kydlaw,  for your reply. By any chance do you use UMAP? I'm trying to use them at the same time but I can find the right combination of Numpy ver that works for both of them.

**Comment by sokolegg** [comment] 2022-01-19 18:41
Hi! Same problem too in docker

python = "^3.8"
requests = "^2.25.1"
grequests = "^0.6.0"
statsd = "^3.3.0"
aiohttp = "^3.7.4"
gunicorn = "^20.1.0"
efficientnet-pytorch = "^0.7.1"
opencv-python = "^4.5.2"
numpy = "^1.20.3"
boto3 = "^1.17.73"
albumentations = "^0.5.2"
tqdm = "^4.60.0"
ftfy = "^6.0.1"
regex = "^2021.4.4"
psutil = "^5.8.0"
objgraph = "^3.5.0"
memory-profiler = "^0.58.0"
Pympler = "^0.9"
Flask = "1.1.2"
decord = "^0.5.2"
scikit-learn = "^0.24.2"
tbb = "^2021.2.0"
uvicorn = "^0.13.4"
python-json-logger = "^2.0.1"
fastapi = "^0.65.1"
torch = "1.7.1"


Docker is simple

FROM python:3.8 ...
without any modifications just poetry install

**Comment by srsani** [comment] 2022-01-20 11:13
@sokolegg the attached `requirements.txt` works with python 3.8.5 in docker `FROM python:3.8.5`

I hope that it helps 

argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
black==21.12b0
bleach==4.1.0
certifi==2021.10.8
cffi==1.15.0
click==8.0.3
cycler==0.11.0
Cython==0.29.26
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.3
executing==0.8.2
hdbscan==0.8.27
importlib-resources==5.4.0
ipykernel==5.1.0
ipython==8.0.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
joblib==1.1.0
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.1
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
llvmlite==0.34.0
MarkupSafe==2.0.1
matplotlib==3.3.2
matplotlib-inline==0.1.3
mistune==0.8.4
mypy-extensions==0.4.3
nbclient==0.5.10
nbconvert==6.4.0
nbformat==5.1.3
nest-asyncio==1.5.4
notebook==6.4.7
numba==0.51.2
numpy==1.22.1
packaging==21.3
pandas==1.1.4
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.0
platformdirs==2.4.1
plotly==4.12.0
prometheus-client==0.12.0
prompt-toolkit==3.0.24
ptyprocess==0.7.0
pure-eval==0.2.1
pycocotools==2.0.4
pycparser==2.21
Pygments==2.11.2
pyparsing==3.0.6
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.3
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.0
retrying==1.3.3
scikit-learn==0.23.2
scipy==1.7.3
Send2Trash==1.8.0
six==1.16.0
stack-data==0.1.4
terminado==0.12.1
testpath==0.5.0
threadpoolctl==3.0.0
tomli==1.2.3
tornado==6.1
traitlets==5.1.1
typing_extensions==4.0.1
umap-learn==0.4.6
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2
zipp==3.7.0
seaborn==0.11.2

**Closed** 2022-01-20 11:13 UTC

**Comment by Liquidmasl** [comment] 2024-12-06 13:18
has this been close because hdbscan now supports numpy 2?
I cant seam to find any concrete information about that, google just points me to here, and this was close without any information as well.
